name: generate ascii character using cowsay
on: push
jobs:
    generate_ascii:
      name: generate ascii
      runs-on: ubuntu-latest
      steps:
        - name: checkout the repo
          uses: actions/checkout@v4
        - name: greet the users
          run: echo "Let's generate some avatars"
        - name: executing shell cmds
          run: |
               ls
               sudo apt-get install cowsay -y
        - name: generating your Avatar
          run: cowsay -f dragon "spit fire like a dragon" >> dragon.txt
        - name: test the file
          run: grep -i "dragon" dragon.txt
        - name: read the lion file
          run: cat dragon.txt
        - name: display the directory
          run: ls -ltra

               

