name: Use of Variables and secrets in a Demo scenario sample
on:
 workflow_dispatch:
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: feliciadeb
  DOCKER_IMAGE: nginx
  
jobs:
  Docker-Build-push:
    name: Docker Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:${{vars.DOCKER_IMAGE_TAG}}
      - name: Docker Login
        run: echo docker login --username=${{env.DOCKER_IMAGE}} --password=${{secrets.DOCKER_REGISTRY_PASSWORD}}
      - name: Docker push
        run: echo docker push docker.io/feliciadeb/nginx:latest
  Deploy:
    name: Docker deploy
    needs: [Docker-Build-push]
    runs-on: ubuntu-latest
    steps:
      - name: Docker deploy
        run: echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:${{vars.DOCKER_IMAGE_TAG}}
